- name: Lookup Plugin File Demo
  hosts: servera*
  gather_facts: no
  become: true
  
  vars:
    someusers:
    - name: Daliann
      uid: 1200
    - name: Jerry
      uid: 1250


  tasks:

  - name: Create  users
    user:
      name: "{{ item.name }}"
      password: "{{ lookup('password', '/home/student/mydir/pass/{{item.name}}.txt chars=ascii_letters encrypt=sha512_crypt length=10')  }}"
      #password: "{{ 'google123' | password_hash('sha512')}}"
      uid: "{{ item.uid }}"
    loop: "{{ someusers }}"

  #- name: Search with query plugin
  #  debug:
  #    msg: "{{ item }}"
  #  when: item.find('Daliann') != -1
  #  loop: "{{ query('lines', 'cat /etc/passwd') }}"
    #
